### ISSUE TITLE
Nice but - " Your connection is not secure " ^^ ssl cert problem ?

### ISSUE THREAD

**Issue by scriptzteam** [azetrix/ShortLink#1]
Nice but - " Your connection is not secure " ^^ ssl cert problem ?

**Comment by PhoenixPeca** [comment]
Yeah, I'm currently performing some server maintenance.. 😄 azetrix.xyz It'll be up and running in 15 minutes.. hahahah!!! Thanks!!!

**Comment by PhoenixPeca** [comment]
Sorry if it took long.. it's fixed now.
