### ISSUE TITLE
Redirect index.php to another site?

### ISSUE THREAD

**Issue by haleyngonadi** [azetrix/ShortLink#2]
Hi. This is an awesome package. Thank you! 
I am wondering if it's possible to sample shortcode redirect to a main site, not just the shortcodes?

for example - test.com (shortcode url) redirect to tester.com (main site url). Make sense?

**Comment by PhoenixPeca** [comment]
Hi,

Yes it is possible... just open the file `inc/vars.php` and set FORWADER_PREVIEW to false.

Thanks!
